name: mercax
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.5.0 <4.4.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.5
  get_storage: ^2.0.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  mobile_scanner: ^6.0.10
  barcode_scan2: ^4.2.0
  image_picker: ^1.0.7
  uuid: ^4.4.0
  flutter_launcher_icons: ^0.14.4
  charts_flutter: ^0.12.0
  http: ^1.1.0
  url_launcher: ^6.2.1
  permission_handler: ^12.0.1
  image: ^4.1.7
  # Dependências para máscaras e validações
  mask_text_input_formatter: ^2.9.0
  # Dependências para geração de PDF e relatórios
  pdf: ^3.10.7
  printing: ^5.12.0
  share_plus: ^7.2.2
  path_provider: ^2.1.2
  intl: ^0.17.0
  # Dependências para notificações e áudio
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  flutter_local_notifications: ^18.0.1
  audioplayers: ^6.1.0
  workmanager: ^0.5.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  mockito: ^5.4.4
  build_runner: ^2.4.8
  integration_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/sounds/

# Configuração do flutter_launcher_icons
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/apenasIcone.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  adaptive_icon_background: "#F5F5F5"
  adaptive_icon_foreground: "assets/images/apenasIcone.png"
  web:
    generate: true
    image_path: "assets/images/apenasIcone.png"
    background_color: "#F5F5F5"
    theme_color: "#F5F5F5"
  windows:
    generate: true
    image_path: "assets/images/apenasIcone.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/apenasIcone.png"
