name: compra_pronta
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.5.0 <4.4.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.5
  get_storage: ^2.0.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  mobile_scanner: ^6.0.10
  barcode_scan2: ^4.2.0
  image_picker: ^1.0.7
  uuid: ^4.4.0
  flutter_launcher_icons: ^0.14.4
  charts_flutter: ^0.12.0
  http: ^1.1.0
  url_launcher: ^6.2.1
  permission_handler: ^12.0.1
  # Dependências para máscaras e validações
  mask_text_input_formatter: ^2.9.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  mockito: ^5.4.4
  build_runner: ^2.4.8
  integration_test:
    sdk: flutter
flutter:
  uses-material-design: true
